"""add_is_simulation_to_incident

Revision ID: 03b100d1bb6a
Revises: 95d4ae1286fa
Create Date: 2026-10-04 23:15:10.790890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b100d1bb6a'
down_revision: Union[str, Sequence[str], None] = '95d4ae1286fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('is_simulation', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_incidents_is_simulation'), 'incidents', ['is_simulation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_is_simulation'), table_name='incidents')
    op.drop_column('incidents', 'is_simulation')
    # ### end Alembic commands ###
