"""add_prevention_fields

Revision ID: d449e463c746
Revises: 03b100d1bb6a
Create Date: 2026-10-04 23:20:50.027848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd449e463c746'
down_revision: Union[str, Sequence[str], None] = '03b100d1bb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocked_sources', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('blocked_sources', sa.Column('is_simulation', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_blocked_sources_is_simulation'), 'blocked_sources', ['is_simulation'], unique=False)
    op.add_column('prevention_actions', sa.Column('is_simulation', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_prevention_actions_is_simulation'), 'prevention_actions', ['is_simulation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prevention_actions_is_simulation'), table_name='prevention_actions')
    op.drop_column('prevention_actions', 'is_simulation')
    op.drop_index(op.f('ix_blocked_sources_is_simulation'), table_name='blocked_sources')
    op.drop_column('blocked_sources', 'is_simulation')
    op.drop_column('blocked_sources', 'provider')
    # ### end Alembic commands ###
